### ISSUE TITLE
Custom RGB Colours?

### ISSUE THREAD

**Issue by PaulWalkerUK** [fej-snikduj/URLColors#1]
Hi,

I wondered if it's possible to specify custom RGB values please?

Thanks,
Paul

**Comment by fej-snikduj** [comment]
Hey @PaulWalkerUK - thanks for the request.  How would you like to be able to input it into the text field?  Can you give an example?

**Comment by PaulWalkerUK** [comment]
I don't really mind to be honest. At the moment, I've got a line:
```
example.com, green
```

Maybe something like:
```
example.com, RGB(60,180,75)
```

**Comment by PaulWalkerUK** [comment]
Never mind, just realised I can specify hex codes, as in:

```
example.com, #f00
```
