### ISSUE TITLE
Empty lines match all pages

### ISSUE THREAD

**Issue by Jysk-MLP** [fej-snikduj/URLColors#12]
![image](https://github.com/fej-snikduj/URLColors/assets/137173568/35293994-4c31-43d0-8aee-a3b8a5c160c1)

How to reproduce:
Set a configuration for a link `google.com, red, flash, 10, 15px, 0.2`
Create a blank line below.

Expected behavior: empty line is ignored as it has no config. This is usually used by people to separate configurations to make it easier to read.

Actual behavior: Empty line is read as a wildcard that matches all links and has no configuration.

**Comment by fej-snikduj** [comment]
Thanks @Jysk-MLP - will investigate and put up a PR today

**Comment by fej-snikduj** [comment]
Fixed this https://github.com/fej-snikduj/URLColors/pull/13 - thanks for reporting.  Will upload and submit for release, release will take a couple days.

**Comment by fej-snikduj** [comment]
Looks like this update has been published already.  For some reason chrome didn't allow me to update so I had to remove and then reinstall

**Comment by Jysk-MLP** [comment]
Tested working on version 2.2
Thank you for the quick support 🙂
