### ISSUE TITLE
Settings seem to reset when chrome crashes

### ISSUE THREAD

**Issue by saveman71** [fej-snikduj/URLColors#2]
I don't really have much more info than this, but over the last month I've had this (amazing) extension installed, I have found myself needing to re-enter my settings twice.

I think this is due to the extension exiting abnormally when chrome crashes?

**Comment by fej-snikduj** [comment]
Please to reopen if this is still an issue.  The settings were stored in localStorage, but now are in chrome.storage on the latest version.  Not sure if this will still be an issue.  Thanks for reporting!
