### ISSUE TITLE
URL not colorized in chrome  76.0.3809.100

### ISSUE THREAD

**Issue by ojdupuis** [fej-snikduj/URLColors#3]
Hello,

the url doesn't seem to be colorized anymore and we get a log in the console of the background page :

```Unchecked runtime.lastError: Cannot access contents of url "chrome-search://local-ntp/local-ntp.html". Extension manifest must request permission to access this host.```

**Comment by fej-snikduj** [comment]
Please reopen if this is still an issue.  Thank you
