### ISSUE TITLE
Settings get erased

### ISSUE THREAD

**Issue by DanielCardillo523** [fej-snikduj/URLColors#7]
Every time I exit chrome, the settings are erased, and I have to set them again when I open it back up. Any idea what the problem could be?

I'm running version 89.0.4389.90 (Official Build) (64-bit). My environment is Windows 8.1.

**Comment by fej-snikduj** [comment]
Hi @DanielCardillo523 - the settings were stored in localStorage, so if that was getting erased ever, the settings would be removed.  The new version is stored in chrome.storage.  But please reopen if you are still experiencing the issue on the new version.
