### ISSUE TITLE
Chrome Web Store has blocked URLColors due to malware

### ISSUE THREAD

**Issue by clnsdrbrg** [fej-snikduj/URLColors#9]
Hi, 
Love this extension and I've gotten so used to using it on my work laptop. Today when I opened the browser, the extension wasn't working anymore and the browser gave me a notice saying "This extension has been disabled because the Chrome Web Store has reported it as unsafe."/"This extension is blocked. Microsoft Edge found that "URLColors" contains malware." (got different messages for different language settings in the browser). 
When trying to go to the page in Chrome Web Store - regardless of browser - I just get error 404. 
I've been using the extension (version 1.1.2) from Chrome Web Store in Microsoft Edge (yeah, yeah, I know..). 
Would it be possible to get a new version that could be approved in Chrome Web Store and Microsoft Edge again?
Kind regards,
Celina

**Comment by vsha041** [comment]
Same as @clnsdrbrg . After I updated my Chrome browser, it stopped working after that. And the URL to the extension doesn't work anymore either.

**Comment by Simon1er** [comment]
Please, make it available again!  It is a so great extension.

**Comment by fej-snikduj** [comment]
Hey all - sorry, I am working on this.  I dropped the ball on some updates Chrome was asking for - they didn't have my correct email so I never got the warnings.  Working to get this fixed

**Comment by fej-snikduj** [comment]
I just submitted the extension for review after providing some privacy policy updates and permission justifications - it may take a couple weeks according to the message I received 😞 - my apologies.

**Comment by mzgajner** [comment]
C'mon, no need to apologize - thanks for doing the extension in the first place.

**Comment by clnsdrbrg** [comment]
Thanks for the quick reply and fix @fej-snikduj!

**Comment by BilThomas** [comment]
Thank you for the quick response.

**Comment by Simon1er** [comment]
Great job!  Thanks!

**Comment by fej-snikduj** [comment]
This should be fixed?  I actually never got a notification from them, but looks like its back in the [webstore](https://chrome.google.com/webstore/detail/urlcolors/jjccpcminoppplpmcfghflolejbdkekm?hl=en-US) :D

**Comment by clnsdrbrg** [comment]
Thank you! :D

> This should be fixed? I actually never got a notification from them, but looks like its back in the webstore :D
